# Generated by Django 3.0.5 on 2020-04-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Naruto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='card_image'),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
