# Generated by Django 3.1 on 2020-09-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Naruto', '0003_auto_20200809_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attack',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='defense',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
