# Generated by Django 3.1 on 2020-09-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Naruto', '0004_auto_20200908_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
