# Generated by Django 3.1 on 2020-09-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Naruto', '0006_auto_20200908_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attack',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='defense',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='card',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
